-- Migration 0001: profile pictures.
--
-- ADDITIVE ONLY. This creates one new table. It does not alter, rename, drop or rewrite any
-- existing table or row, so it is safe to apply to the live shared `nova-help` database while
-- Nova.Help is running: Nova.Help never reads this table, and code that predates it is
-- unaffected by its existence. Re-running it is a no-op (IF NOT EXISTS).
--
-- A picture's BYTES live in R2, never here. This row is only the reference: which object, what
-- type we determined it to be, how big it is.
--
-- ON DELETE CASCADE: deleting an account removes its row. The R2 object is removed by the
-- account-deletion route, which reads this row first.
--
-- Apply (when a deployment is approved, not before):
--   npx wrangler d1 execute nova-help --remote --file packages/nova-accounts/migrations/0001_account_avatars.sql
-- Roll back (nothing else depends on it):
--   DROP TABLE account_avatars;

CREATE TABLE IF NOT EXISTS account_avatars (
  account_id   TEXT PRIMARY KEY REFERENCES accounts(id) ON DELETE CASCADE,
  -- avatars/<accountId>/<48 hex>, generated by avatars.mjs and never from a request.
  object_key   TEXT    NOT NULL,
  -- One of image/png, image/jpeg, image/webp, decided from the file's own bytes.
  content_type TEXT    NOT NULL,
  size         INTEGER NOT NULL,
  updated_at   TEXT    NOT NULL
);
